/* eslint-disable @typescript-eslint/ban-ts-comment */
import Head from 'next/head'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Form } from '@/features/AiImage/components/Form'
import { useBlockchain } from '@/hooks/useBlockchain'
import { useNFT } from '@/features/NftMinting/hooks/useNFT';
import { Collection } from '@/features/NftMinting/components/Collection';
import { Navbar } from '@/layouts/Navbar';

export default function Home() {
  const { ownerAddress, loadBlockchainData, provider, smartContract } = useBlockchain()
  const { collection, isFetchingNft, mintNFT } = useNFT(smartContract, provider, ownerAddress)
  return (
    <>
      <Head>
        <title>Ai NFT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <Navbar loadBlockchainData={ loadBlockchainData } ownerAddress={ ownerAddress } />
        <div>
          <Form ownerAddress={ ownerAddress } mintNFT={ mintNFT } />
          <hr className='mt-8 mb-4' />
          <Collection ownerAddress={ ownerAddress } collection={ collection } isFetchingNft={ isFetchingNft } />
        </div>
        <ToastContainer role="alert" theme='colored' position='top-left' />
      </main>
    </>
  )
}
